-- digimon_type: Digimon Official Encyclopedia (reference_en)
-- evolution_condition: Skullbot Time Stranger chart (https://api.skullbot.fr/digimon/)

UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, HP >= 1610, SPI >= 1010' WHERE id = 1;
UPDATE digimon_en SET digimon_type = 'Mammal', evolution_condition = 'Agent Rank >= 1, SPI >= 240' WHERE id = 2;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 3, MP >= 470, SPD >= 640' WHERE id = 3;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 5, HP >= 1530, SPI >= 1000, SPD >= 890' WHERE id = 4;
UPDATE digimon_en SET digimon_type = 'Mineral', evolution_condition = 'Agent Rank >= 3, DEF >= 480' WHERE id = 5;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, INT >= 870, SPI >= 960' WHERE id = 6;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 1, DEF >= 200' WHERE id = 9;
UPDATE digimon_en SET digimon_type = 'Fire', evolution_condition = 'Agent Rank >= 3, ATK >= 530, SPI >= 450' WHERE id = 10;
UPDATE digimon_en SET digimon_type = 'Mythical Beast', evolution_condition = 'Agent Rank >= 3, SPD >= 380' WHERE id = 11;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, DEF >= 300, SPD >= 400' WHERE id = 12;
UPDATE digimon_en SET digimon_type = 'Ghost', evolution_condition = 'Agent Rank >= 3, SPI >= 400' WHERE id = 13;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 3, MP >= 420' WHERE id = 14;
UPDATE digimon_en SET digimon_type = 'Giant Bird', evolution_condition = 'Agent Rank >= 3, DEF >= 300, SPD >= 470' WHERE id = 15;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 3, HP >= 1090' WHERE id = 16;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 3, ATK >= 660' WHERE id = 17;
UPDATE digimon_en SET digimon_type = 'Beast Dragon', evolution_condition = 'Agent Rank >= 7, HP >= 2700, ATK >= 2220' WHERE id = 19;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, MP >= 280, SPD >= 180' WHERE id = 20;
UPDATE digimon_en SET digimon_type = 'Sea Animal', evolution_condition = 'Agent Rank >= 5, HP >= 1800, INT >= 990, SPI >= 960' WHERE id = 21;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, Stingmon''s personnality is Tolerant, ExVeemon''s personnality is Zealous, DNA Digivolution' WHERE id = 23;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 7, INT >= 1800, SPI >= 2040' WHERE id = 24;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 3, HP >= 1090' WHERE id = 25;
UPDATE digimon_en SET digimon_type = 'Warrior', evolution_condition = 'Agent Rank >= 5, ATK >= 960, SPD >= 960' WHERE id = 26;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 7, HP >= 2350, ATK >= 2430' WHERE id = 27;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, HP >= 1650, DEF >= 940' WHERE id = 28;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 3, SPD >= 620' WHERE id = 30;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, SPI >= 890, SPD >= 1100' WHERE id = 31;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 7, MP >= 1140, ATK >= 1300, INT >= 1590' WHERE id = 32;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, ATK >= 970, DEF >= 1060' WHERE id = 33;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, MP >= 1300, INT >= 2180, SPD >= 1860' WHERE id = 34;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, HP >= 2500, ATK >= 2340, SPD >= 1330' WHERE id = 35;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, MP >= 1060, INT >= 2290' WHERE id = 36;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, HP >= 2860, ATK >= 2000, DEF >= 1430' WHERE id = 37;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, HP >= 2000, ATK >= 1970, INT >= 1900' WHERE id = 38;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, MP >= 920, INT >= 1820' WHERE id = 39;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 8, HP >= 4680, ATK >= 2070' WHERE id = 40;
UPDATE digimon_en SET digimon_type = 'Puppet', evolution_condition = 'Agent Rank >= 5, DEF >= 860, INT >= 850, SPI >= 900' WHERE id = 41;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 1, INT >= 200, SPD >= 170' WHERE id = 42;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 3, SPI >= 530' WHERE id = 43;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, MP >= 620, DEF >= 940' WHERE id = 44;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 10, Valor Agent Skills learned = 46, Philanthropy Agent Skills learned = 46, Amicability Agent Skills learned = 46, Wisdom Agent Skills learned = 46' WHERE id = 45;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 10, Valor Agent Skills learned = 46, Philanthropy Agent Skills learned = 46, Amicability Agent Skills learned = 46, Wisdom Agent Skills learned = 46' WHERE id = 46;
UPDATE digimon_en SET digimon_type = 'Evil Dragon', evolution_condition = 'Agent Rank >= 7, HP >= 2960, ATK >= 2290' WHERE id = 47;
UPDATE digimon_en SET digimon_type = 'Holy Dragon', evolution_condition = 'Agent Rank >= 7, HP >= 2690, INT >= 1660, SPI >= 1380' WHERE id = 48;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 7, HP >= 2620, ATK >= 2290' WHERE id = 49;
UPDATE digimon_en SET digimon_type = 'Reptile', evolution_condition = 'Agent Rank >= 1, HP >= 530' WHERE id = 50;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 3, HP >= 940, SPI >= 450' WHERE id = 51;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 1, HP >= 400, DEF >= 180' WHERE id = 52;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 1, MP >= 480, INT >= 250' WHERE id = 53;
UPDATE digimon_en SET digimon_type = 'Dinosaur', evolution_condition = 'Agent Rank >= 3, HP >= 1100' WHERE id = 54;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, ATK >= 210, SPD >= 210' WHERE id = 55;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 1, HP >= 500, SPI >= 160' WHERE id = 56;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 7, MP >= 2350, ATK >= 1290, INT >= 1500' WHERE id = 57;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 3, MP >= 360, INT >= 630, SPI >= 480' WHERE id = 58;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, HP >= 2080, ATK >= 980' WHERE id = 59;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, ATK >= 1430, DEF >= 1790, SPI >= 1730' WHERE id = 60;
UPDATE digimon_en SET digimon_type = 'Puppet', evolution_condition = 'Agent Rank >= 5, HP >= 2080, SPI >= 1140' WHERE id = 61;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, SPI >= 470' WHERE id = 68;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 7, DEF >= 2220' WHERE id = 69;
UPDATE digimon_en SET digimon_type = 'Mollusk', evolution_condition = 'Agent Rank >= 3, MP >= 330' WHERE id = 70;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, ATK >= 940, SPD >= 980' WHERE id = 71;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 3, ATK >= 510' WHERE id = 72;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 5, MP >= 880, INT >= 1260' WHERE id = 73;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, HP >= 1800, SPD >= 1060' WHERE id = 74;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, MP >= 1190, ATK >= 1940, SPI >= 1710' WHERE id = 75;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 5, HP >= 1630, SPD >= 980' WHERE id = 76;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 3, HP >= 820, SPI >= 540' WHERE id = 77;
UPDATE digimon_en SET digimon_type = 'Dark Dragon', evolution_condition = 'Agent Rank >= 3, HP >= 1100' WHERE id = 78;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, ATK >= 980, DEF >= 1020, SPI >= 980' WHERE id = 79;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, ATK >= 1150, SPD >= 2100' WHERE id = 80;
UPDATE digimon_en SET digimon_type = 'Little Devil', evolution_condition = 'Agent Rank >= 1, MP >= 400, INT >= 270' WHERE id = 81;
UPDATE digimon_en SET digimon_type = 'Mythical Beast', evolution_condition = 'Agent Rank >= 5, INT >= 1050, SPD >= 1020' WHERE id = 82;
UPDATE digimon_en SET digimon_type = 'Mythical Beast', evolution_condition = 'Agent Rank >= 7, MP >= 1160, SPD >= 1750' WHERE id = 83;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 5, ATK >= 900, INT >= 900, SPD >= 1100' WHERE id = 84;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, HP >= 1650, INT >= 950' WHERE id = 85;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, DEF >= 1730, INT >= 1800, SPD >= 2060' WHERE id = 86;
UPDATE digimon_en SET digimon_type = 'Angel', evolution_condition = 'Agent Rank >= 3, MP >= 730, INT >= 540' WHERE id = 87;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 8, WarGreymon''s personnality is Daring, MetalGarurumon''s personnality is Friendly, DNA Digivolution' WHERE id = 88;
UPDATE digimon_en SET digimon_type = 'Reptile', evolution_condition = 'Agent Rank >= 1, ATK >= 280' WHERE id = 90;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 3, ATK >= 500, SPI >= 590' WHERE id = 91;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 3, HP >= 820, SPI >= 540' WHERE id = 92;
UPDATE digimon_en SET digimon_type = 'Dark Angel', evolution_condition = 'Agent Rank >= 3, MP >= 640, SPD >= 430' WHERE id = 93;
UPDATE digimon_en SET digimon_type = 'Shining Dragon', evolution_condition = 'Agent Rank >= 7, HP >= 2300, ATK >= 2360' WHERE id = 94;
UPDATE digimon_en SET digimon_type = 'Beast Knight', evolution_condition = 'Agent Rank >= 7, HP >= 2470, SPD >= 1790' WHERE id = 95;
UPDATE digimon_en SET digimon_type = 'Mammal', evolution_condition = 'Agent Rank >= 1, MP >= 600, INT >= 360' WHERE id = 96;
UPDATE digimon_en SET digimon_type = 'Little Devil', evolution_condition = 'Agent Rank >= 1, ATK >= 230, INT >= 350' WHERE id = 97;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, HP >= 2010, DEF >= 1740, SPI >= 1870' WHERE id = 98;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 3, SPD >= 610' WHERE id = 100;
UPDATE digimon_en SET digimon_type = 'High Angel', evolution_condition = 'Agent Rank >= 5, MP >= 910, INT >= 1270' WHERE id = 101;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 3, HP >= 820, MP >= 380, ATK >= 530' WHERE id = 102;
UPDATE digimon_en SET digimon_type = 'Crustacean', evolution_condition = 'Agent Rank >= 1, ATK >= 150, DEF >= 160' WHERE id = 103;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 8, EmperorGreymon''s personnality is Zealous, MagnaGarurumon''s personnality is Friendly, DNA Digivolution' WHERE id = 104;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 8, ATK >= 2810, INT >= 3170' WHERE id = 105;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, HP >= 4450, ATK >= 3980' WHERE id = 106;
UPDATE digimon_en SET digimon_type = 'Dark Angel', evolution_condition = 'Agent Rank >= 5, HP >= 1290, INT >= 770, SPD >= 830' WHERE id = 107;
UPDATE digimon_en SET digimon_type = 'Demon', evolution_condition = 'Agent Rank >= 1, HP >= 500, DEF >= 200' WHERE id = 111;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, ATK >= 260' WHERE id = 112;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 3, INT >= 300, SPI >= 300' WHERE id = 113;
UPDATE digimon_en SET digimon_type = 'Mini Dragon', evolution_condition = 'Agent Rank >= 1, ATK >= 280, SPD >= 170' WHERE id = 114;
UPDATE digimon_en SET digimon_type = 'Dinosaur', evolution_condition = 'Agent Rank >= 3, ATK >= 700, SPI >= 540' WHERE id = 115;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 5, ATK >= 1020, SPI >= 890, SPD >= 1060' WHERE id = 116;
UPDATE digimon_en SET digimon_type = 'Holy Bird', evolution_condition = 'Agent Rank >= 7, INT >= 1800, SPI >= 1750, SPD >= 1640' WHERE id = 117;
UPDATE digimon_en SET digimon_type = 'Unique', evolution_condition = 'Agent Rank >= 8, BanchoLeomon''s personnality is Daring, Varodurumon''s personnality is Sociable, DNA Digivolution' WHERE id = 118;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, ATK >= 1800, SPI >= 2240' WHERE id = 126;
UPDATE digimon_en SET digimon_type = 'Puppet', evolution_condition = 'Agent Rank >= 7, ATK >= 1640, DEF >= 1790' WHERE id = 127;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 7, HP >= 2500, ATK >= 1490, SPD >= 1620' WHERE id = 128;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, MP >= 820, INT >= 930, SPI >= 940' WHERE id = 129;
UPDATE digimon_en SET digimon_type = 'Ancient Fish', evolution_condition = 'Agent Rank >= 3, HP >= 1060' WHERE id = 130;
UPDATE digimon_en SET digimon_type = 'Aquatic', evolution_condition = 'Agent Rank >= 5, MP >= 900, INT >= 1040' WHERE id = 132;
UPDATE digimon_en SET digimon_type = 'Aquatic', evolution_condition = 'Agent Rank >= 5, HP >= 1680, INT >= 1200' WHERE id = 133;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, HP >= 1730, DEF >= 1060' WHERE id = 134;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, MP >= 1700, ATK >= 960, SPD >= 1850' WHERE id = 135;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, ATK >= 220, DEF >= 190' WHERE id = 136;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, ATK >= 700' WHERE id = 137;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 5, HP >= 1860, ATK >= 980, DEF >= 890' WHERE id = 138;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Friendship' WHERE id = 139;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, HP >= 1840, ATK >= 990, SPD >= 1090' WHERE id = 140;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Love' WHERE id = 141;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Sincerity' WHERE id = 142;
UPDATE digimon_en SET digimon_type = 'Reptile', evolution_condition = 'Agent Rank >= 1, ATK >= 490' WHERE id = 143;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Knowledge' WHERE id = 144;
UPDATE digimon_en SET digimon_type = 'Aquatic', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Reliability' WHERE id = 145;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Hope' WHERE id = 146;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Light' WHERE id = 147;
UPDATE digimon_en SET digimon_type = 'High Angel', evolution_condition = 'Agent Rank >= 5, INT >= 970, SPI >= 910' WHERE id = 148;
UPDATE digimon_en SET digimon_type = 'Dark Dragon', evolution_condition = 'Agent Rank >= 5, HP >= 1960, ATK >= 780' WHERE id = 149;
UPDATE digimon_en SET digimon_type = 'Dark Knight', evolution_condition = 'Agent Rank >= 7, ATK >= 1870, INT >= 1430' WHERE id = 150;
UPDATE digimon_en SET digimon_type = 'Reptile', evolution_condition = 'Agent Rank >= 1, MP >= 230, ATK >= 250' WHERE id = 151;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 3, MP >= 1580, INT >= 1130' WHERE id = 162;
UPDATE digimon_en SET digimon_type = 'Aquatic', evolution_condition = 'Agent Rank >= 3' WHERE id = 163;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 9, Valor Agent Skills learned = 46, Philanthropy Agent Skills learned = 46, Amicability Agent Skills learned = 46, Wisdom Agent Skills learned = 46' WHERE id = 168;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 9, HP >= 4020, ATK >= 3200' WHERE id = 169;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, MP >= 1100, INT >= 1370' WHERE id = 170;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, INT >= 3380, SPI >= 2920' WHERE id = 171;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, MP >= 1170, SPI >= 2040' WHERE id = 172;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, ATK >= 2220, SPI >= 1810' WHERE id = 173;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, MP >= 960, ATK >= 2220' WHERE id = 174;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 7, ATK >= 2420, DEF >= 2060' WHERE id = 175;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, HP >= 2470, SPI >= 2190' WHERE id = 176;
UPDATE digimon_en SET digimon_type = 'Fire', evolution_condition = 'Agent Rank >= 5, HP >= 1370, MP >= 1020' WHERE id = 177;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, DEF >= 1700, SPI >= 1820' WHERE id = 178;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, HP >= 2880, ATK >= 1790, INT >= 1510' WHERE id = 179;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, HP >= 2460, ATK >= 2500, INT >= 1700' WHERE id = 180;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 8, ATK >= 3470, SPD >= 2960' WHERE id = 181;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, HP >= 2760, SPI >= 1680, SPD >= 1720' WHERE id = 182;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 9, MP >= 470, Valor Agent Skills learned = 46' WHERE id = 183;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 9, ATK >= 1100, SPD >= 1090, Valor Agent Skills learned = 46, Philanthropy Agent Skills learned = 46' WHERE id = 184;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 9, ATK >= 3070, INT >= 2980, Valor Agent Skills learned = 46, Amicability Agent Skills learned = 46, Wisdom Agent Skills learned = 46' WHERE id = 185;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 9, INT >= 2980, SPI >= 2890, Valor Agent Skills learned = 46, Philanthropy Agent Skills learned = 46, Amicability Agent Skills learned = 46' WHERE id = 186;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 9, MP >= 1820, ATK >= 3070, Valor Agent Skills learned = 46, Amicability Agent Skills learned = 46' WHERE id = 187;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 9, HP >= 4620, SPD >= 2910, Valor Agent Skills learned = 46, Wisdom Agent Skills learned = 46' WHERE id = 188;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, MP >= 1670, INT >= 2500' WHERE id = 189;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, HP >= 520, ATK >= 250' WHERE id = 190;
UPDATE digimon_en SET digimon_type = 'Beast Dragon', evolution_condition = 'Agent Rank >= 3, DEF >= 460' WHERE id = 191;
UPDATE digimon_en SET digimon_type = 'Beast Dragon', evolution_condition = 'Agent Rank >= 5, ATK >= 900, DEF >= 960' WHERE id = 192;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, HP >= 1850, ATK >= 2150, DEF >= 1860' WHERE id = 193;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 7, MP >= 1300, ATK >= 2130' WHERE id = 194;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 7, HP >= 2200, MP >= 1380, ATK >= 1600' WHERE id = 195;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 7, HP >= 2690, ATK >= 1790' WHERE id = 196;
UPDATE digimon_en SET digimon_type = 'Giant Bird', evolution_condition = 'Agent Rank >= 7, HP >= 2260, DEF >= 1720, SPI >= 2060' WHERE id = 197;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 5, HP >= 1650, DEF >= 980' WHERE id = 198;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 5, ATK >= 1110, SPD >= 1060' WHERE id = 199;
UPDATE digimon_en SET digimon_type = 'Dragon', evolution_condition = 'Agent Rank >= 1, ATK >= 270, SPD >= 170' WHERE id = 208;
UPDATE digimon_en SET digimon_type = 'Dragon', evolution_condition = 'Agent Rank >= 3, ATK >= 830' WHERE id = 209;
UPDATE digimon_en SET digimon_type = 'Sky Dragon', evolution_condition = 'Agent Rank >= 5, HP >= 1760, SPD >= 1020' WHERE id = 210;
UPDATE digimon_en SET digimon_type = 'Earth Dragon', evolution_condition = 'Agent Rank >= 5, HP >= 2120, ATK >= 740, DEF >= 870' WHERE id = 211;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 7, ATK >= 2280, SPD >= 2280' WHERE id = 213;
UPDATE digimon_en SET digimon_type = 'Machine Dragon', evolution_condition = 'Agent Rank >= 7, HP >= 1920, ATK >= 1920, DEF >= 1570' WHERE id = 214;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 8, Slayerdramon''s personnality is Daring, Breakdramon''s personnality is Reckless, DNA Digivolution' WHERE id = 215;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, MP >= 970, ATK >= 900' WHERE id = 217;
UPDATE digimon_en SET digimon_type = 'Dragon', evolution_condition = 'Agent Rank >= 3, HP >= 1060' WHERE id = 218;
UPDATE digimon_en SET digimon_type = 'Reptile', evolution_condition = 'Agent Rank >= 1, DEF >= 220, SPI >= 140' WHERE id = 219;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 3, SPI >= 560' WHERE id = 220;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 3, SPD >= 620' WHERE id = 222;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 5, MP >= 620, ATK >= 940, SPD >= 890' WHERE id = 223;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5' WHERE id = 224;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 7, HP >= 2380, ATK >= 1960, SPD >= 1060' WHERE id = 225;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, MP >= 530, DEF >= 920, SPI >= 870' WHERE id = 226;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 7, HP >= 2460, INT >= 1360, SPI >= 1820' WHERE id = 227;
UPDATE digimon_en SET digimon_type = 'Composite', evolution_condition = 'Agent Rank >= 3, HP >= 1100' WHERE id = 228;
UPDATE digimon_en SET digimon_type = 'Composite', evolution_condition = 'Agent Rank >= 5, HP >= 2030, ATK >= 1350' WHERE id = 229;
UPDATE digimon_en SET digimon_type = 'Composite', evolution_condition = 'Agent Rank >= 7, Machinedramon''s personnality is Reckless, Kimeramon''s personnality is Friendly, DNA Digivolution' WHERE id = 230;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 1, MP >= 360, INT >= 220' WHERE id = 231;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 5, HP >= 1530, SPI >= 1020, SPD >= 910' WHERE id = 232;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 7, HP >= 2200, ATK >= 2140, INT >= 2770' WHERE id = 233;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, ATK >= 220' WHERE id = 234;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, DEF >= 460' WHERE id = 235;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 5, ATK >= 1070, INT >= 1030, SPI >= 940' WHERE id = 237;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, DEF >= 1100, SPD >= 740' WHERE id = 239;
UPDATE digimon_en SET digimon_type = 'Mollusk', evolution_condition = 'Agent Rank >= 3, HP >= 1010, DEF >= 430' WHERE id = 240;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 1' WHERE id = 241;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, SPI >= 140' WHERE id = 242;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, ATK >= 1050, SPI >= 940' WHERE id = 301;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, HP >= 1480, ATK >= 1300' WHERE id = 302;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 1, DEF >= 170, INT >= 250' WHERE id = 303;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 3, MP >= 380' WHERE id = 304;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 5, MP >= 620, DEF >= 1020' WHERE id = 305;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 7, DEF >= 2280, INT >= 1570' WHERE id = 306;
UPDATE digimon_en SET digimon_type = 'Baby Bird', evolution_condition = 'Agent Rank >= 1, MP >= 270, INT >= 240' WHERE id = 307;
UPDATE digimon_en SET digimon_type = 'Giant Bird', evolution_condition = 'Agent Rank >= 3, MP >= 540, INT >= 540' WHERE id = 308;
UPDATE digimon_en SET digimon_type = 'Bird Man', evolution_condition = 'Agent Rank >= 5, INT >= 1060, SPD >= 980' WHERE id = 309;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 7, MP >= 1260, INT >= 2350' WHERE id = 310;
UPDATE digimon_en SET digimon_type = 'Puppet', evolution_condition = 'Agent Rank >= 5, HP >= 1730, SPI >= 940, SPD >= 860' WHERE id = 311;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, HP >= 2470, DEF >= 2010' WHERE id = 312;
UPDATE digimon_en SET digimon_type = 'Abnormal', evolution_condition = 'Agent Rank >= 3, DEF >= 300' WHERE id = 313;
UPDATE digimon_en SET digimon_type = 'Carnivorous Vegetation', evolution_condition = 'Agent Rank >= 3, HP >= 800' WHERE id = 314;
UPDATE digimon_en SET digimon_type = 'Seraph', evolution_condition = 'Agent Rank >= 7, MP >= 1380, INT >= 1990, SPI >= 1730' WHERE id = 315;
UPDATE digimon_en SET digimon_type = 'Slime', evolution_condition = 'Agent Rank >= 1' WHERE id = 316;
UPDATE digimon_en SET digimon_type = 'Slime', evolution_condition = 'Agent Rank >= 1' WHERE id = 317;
UPDATE digimon_en SET digimon_type = 'Slime', evolution_condition = 'Agent Rank >= 1' WHERE id = 320;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, MP >= 250' WHERE id = 321;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, HP >= 350, ATK >= 150' WHERE id = 322;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, MP >= 400, SPD >= 150' WHERE id = 325;
UPDATE digimon_en SET digimon_type = 'Dinosaur', evolution_condition = 'Agent Rank >= 3, HP >= 1120' WHERE id = 326;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, ATK >= 1220, INT >= 740' WHERE id = 327;
UPDATE digimon_en SET digimon_type = 'Unidentified', evolution_condition = 'Agent Rank >= 8, MP >= 2660, INT >= 3100' WHERE id = 328;
UPDATE digimon_en SET digimon_type = 'Ancient Mutant', evolution_condition = 'Agent Rank >= 7, INT >= 3100, SPI >= 2090' WHERE id = 338;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 3, DEF >= 440' WHERE id = 341;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, DEF >= 810, SPI >= 1040' WHERE id = 342;
UPDATE digimon_en SET digimon_type = 'Sea Beast', evolution_condition = 'Agent Rank >= 1, HP >= 750' WHERE id = 343;
UPDATE digimon_en SET digimon_type = 'Sea Beast', evolution_condition = 'Agent Rank >= 3, HP >= 1120, ATK >= 440' WHERE id = 344;
UPDATE digimon_en SET digimon_type = 'Sea Beast', evolution_condition = 'Agent Rank >= 5, HP >= 1730, ATK >= 930, DEF >= 940' WHERE id = 345;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 7, HP >= 3180, ATK >= 1930' WHERE id = 346;
UPDATE digimon_en SET digimon_type = 'Aquatic', evolution_condition = 'Agent Rank >= 3, HP >= 890, INT >= 420' WHERE id = 347;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 1, ATK >= 220, INT >= 220' WHERE id = 348;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 3, HP >= 840, DEF >= 410' WHERE id = 349;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 5, MP >= 960, SPI >= 830' WHERE id = 359;
UPDATE digimon_en SET digimon_type = 'Mammal', evolution_condition = 'Agent Rank >= 1, INT >= 280' WHERE id = 361;
UPDATE digimon_en SET digimon_type = 'Dinosaur', evolution_condition = 'Agent Rank >= 3, ATK >= 840' WHERE id = 363;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, ATK >= 740, DEF >= 1060, SPI >= 820' WHERE id = 364;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 3, SPD >= 610' WHERE id = 365;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 3, ATK >= 550' WHERE id = 367;
UPDATE digimon_en SET digimon_type = 'Mollusk', evolution_condition = 'Agent Rank >= 3, MP >= 460, DEF >= 430' WHERE id = 368;
UPDATE digimon_en SET digimon_type = 'Armored Dragon', evolution_condition = 'Agent Rank >= 3, ATK >= 510' WHERE id = 369;
UPDATE digimon_en SET digimon_type = 'Ice-Snow', evolution_condition = 'Agent Rank >= 3, HP >= 960, SPI >= 300' WHERE id = 370;
UPDATE digimon_en SET digimon_type = 'Rare Animal', evolution_condition = 'Agent Rank >= 3, HP >= 1200' WHERE id = 371;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 3, ATK >= 550, SPD >= 330' WHERE id = 372;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, MP >= 450, DEF >= 300' WHERE id = 373;
UPDATE digimon_en SET digimon_type = 'Perfect', evolution_condition = 'Agent Rank >= 5, DEF >= 1100, SPI >= 870' WHERE id = 374;
UPDATE digimon_en SET digimon_type = 'Invader', evolution_condition = 'Agent Rank >= 3, HP >= 840, DEF >= 280' WHERE id = 375;
UPDATE digimon_en SET digimon_type = 'Amphibian', evolution_condition = 'Agent Rank >= 5, HP >= 1630, DEF >= 940, SPI >= 940' WHERE id = 376;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 3, MP >= 500, INT >= 630' WHERE id = 377;
UPDATE digimon_en SET digimon_type = 'Bird', evolution_condition = 'Agent Rank >= 5, HP >= 1700, MP >= 650' WHERE id = 378;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 5, MP >= 980, DEF >= 950' WHERE id = 379;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, HP >= 1880, MP >= 1020' WHERE id = 380;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, Have Digi-Egg of Miracles' WHERE id = 382;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, HP >= 2830, ATK >= 1860, DEF >= 2050' WHERE id = 383;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 7, ATK >= 1700, DEF >= 2140' WHERE id = 385;
UPDATE digimon_en SET digimon_type = 'Slime', evolution_condition = 'Agent Rank >= 1' WHERE id = 387;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, HP >= 400' WHERE id = 388;
UPDATE digimon_en SET digimon_type = 'Amphibian', evolution_condition = 'Agent Rank >= 1, MP >= 200' WHERE id = 389;
UPDATE digimon_en SET digimon_type = 'Angel', evolution_condition = 'Agent Rank >= 5, INT >= 430, Talent >= 30' WHERE id = 390;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 1, MP >= 380, INT >= 230' WHERE id = 391;
UPDATE digimon_en SET digimon_type = 'Larva', evolution_condition = 'Agent Rank >= 1, ATK >= 190, SPI >= 190' WHERE id = 392;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 3, HP >= 1100' WHERE id = 393;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 3, ATK >= 440, DEF >= 290' WHERE id = 394;
UPDATE digimon_en SET digimon_type = 'Mysterious Beast', evolution_condition = 'Agent Rank >= 3, INT >= 730' WHERE id = 395;
UPDATE digimon_en SET digimon_type = 'Beast Dragon', evolution_condition = 'Agent Rank >= 3, HP >= 1060' WHERE id = 396;
UPDATE digimon_en SET digimon_type = 'Mythical Dragon', evolution_condition = 'Agent Rank >= 3, MP >= 380, ATK >= 480, SPI >= 390' WHERE id = 397;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 3, MP >= 450' WHERE id = 398;
UPDATE digimon_en SET digimon_type = 'Amphibian', evolution_condition = 'Agent Rank >= 3, INT >= 490' WHERE id = 399;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, HP >= 1580, ATK >= 1130, SPD >= 1020' WHERE id = 400;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, ATK >= 1170, DEF >= 1020' WHERE id = 401;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, ATK >= 1130, DEF >= 990, SPI >= 860' WHERE id = 402;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 5, HP >= 1080, ATK >= 940' WHERE id = 403;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, ATK >= 1250, DEF >= 1060' WHERE id = 404;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 5, MP >= 860, INT >= 1020' WHERE id = 405;
UPDATE digimon_en SET digimon_type = 'Fire', evolution_condition = 'Agent Rank >= 5, HP >= 1720, ATK >= 1020, DEF >= 820' WHERE id = 406;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, HP >= 1370, ATK >= 850' WHERE id = 407;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 5, ExVeemon''s personnality is Zealous, Stingmon''s personnality is Tolerant, DNA Digivolution' WHERE id = 408;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 5, MP >= 540, SPI >= 940, SPD >= 890' WHERE id = 409;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 5, HP >= 1600, INT >= 980, SPI >= 930' WHERE id = 410;
UPDATE digimon_en SET digimon_type = 'Alien', evolution_condition = 'Agent Rank >= 5, MP >= 580, INT >= 860, SPI >= 700' WHERE id = 411;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, HP >= 1720, MP >= 580, DEF >= 1020' WHERE id = 412;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, ATK >= 820, INT >= 630' WHERE id = 413;
UPDATE digimon_en SET digimon_type = 'Giant Bird', evolution_condition = 'Agent Rank >= 5, INT >= 980, SPD >= 1060' WHERE id = 414;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, HP >= 2200, DEF >= 1580, SPI >= 1580' WHERE id = 416;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, HP >= 2960, SPD >= 1980' WHERE id = 417;
UPDATE digimon_en SET digimon_type = 'Ancient Dragon Man', evolution_condition = 'Agent Rank >= 7, ATK >= 2500' WHERE id = 419;
UPDATE digimon_en SET digimon_type = 'Ancient Holy Knight', evolution_condition = 'Agent Rank >= 8, HP >= 4680, SPD >= 2740, Have Omni Blade' WHERE id = 420;
UPDATE digimon_en SET digimon_type = 'Super Angel', evolution_condition = 'Agent Rank >= 7, INT >= 2450, SPI >= 2010' WHERE id = 421;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 7, HP >= 2100, ATK >= 2130, DEF >= 1700' WHERE id = 422;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 7, HP >= 2770, DEF >= 2290' WHERE id = 423;
UPDATE digimon_en SET digimon_type = 'Ancient Beast', evolution_condition = 'Agent Rank >= 7, HP >= 2400, ATK >= 1930, SPD >= 1860' WHERE id = 424;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, INT >= 2710, SPD >= 1990' WHERE id = 425;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, HP >= 2500, SPI >= 1780' WHERE id = 426;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 7, MP >= 1190, INT >= 1860' WHERE id = 427;
UPDATE digimon_en SET digimon_type = 'Puppet', evolution_condition = 'Agent Rank >= 7, DEF >= 1430, SPI >= 1430' WHERE id = 428;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 7, HP >= 2140, DEF >= 1530' WHERE id = 429;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, HP >= 2380, ATK >= 1570, DEF >= 2010' WHERE id = 431;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, MP >= 1430, INT >= 1530' WHERE id = 434;
UPDATE digimon_en SET digimon_type = 'Demon God', evolution_condition = 'Agent Rank >= 8, HP >= 2350, INT >= 3090, SPD >= 1880' WHERE id = 435;
UPDATE digimon_en SET digimon_type = 'Slime', evolution_condition = 'Agent Rank >= 1' WHERE id = 437;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, ATK >= 200' WHERE id = 438;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, MP >= 1180, INT >= 1740, SPI >= 1540' WHERE id = 439;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, HP >= 3220, ATK >= 1680' WHERE id = 440;
UPDATE digimon_en SET digimon_type = 'Plesiosaur', evolution_condition = 'Agent Rank >= 7, HP >= 2680, INT >= 1830, SPI >= 1660' WHERE id = 450;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, MP >= 1500, INT >= 2420, SPI >= 1570' WHERE id = 451;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 3, HP >= 1020, SPI >= 460' WHERE id = 452;
UPDATE digimon_en SET digimon_type = 'Holy Dragon', evolution_condition = 'Agent Rank >= 7, HP >= 2740, MP >= 1100, INT >= 1370' WHERE id = 453;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 3, HP >= 800, ATK >= 520' WHERE id = 454;
UPDATE digimon_en SET digimon_type = 'Crustacean', evolution_condition = 'Agent Rank >= 3, MP >= 390, DEF >= 300' WHERE id = 455;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 3, SPI >= 560' WHERE id = 456;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 1, MP >= 230, ATK >= 270' WHERE id = 457;
UPDATE digimon_en SET digimon_type = 'Mini Dragon', evolution_condition = 'Agent Rank >= 1, HP >= 530, ATK >= 240' WHERE id = 458;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 7, HP >= 2570, ATK >= 1580, DEF >= 1650' WHERE id = 461;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 3, HP >= 1000' WHERE id = 463;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 5, HP >= 2000, SPI >= 920' WHERE id = 465;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, HP >= 350, ATK >= 180' WHERE id = 466;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 3, HP >= 1740, ATK >= 530' WHERE id = 474;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 5, ATK >= 840, SPD >= 1010' WHERE id = 479;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 5, HP >= 1200, ATK >= 1020' WHERE id = 484;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, ATK >= 3630, Valor Agent Skills learned = 46' WHERE id = 489;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, DEF >= 2260, Amicability Agent Skills learned = 46' WHERE id = 490;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 5, DEF >= 1050, SPI >= 970' WHERE id = 491;
UPDATE digimon_en SET digimon_type = 'Dark Beast', evolution_condition = 'Agent Rank >= 7, HP >= 2820, ATK >= 1930, SPD >= 1540' WHERE id = 492;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, Craniamon''s personnality is Devoted, Enbarrmon''s personnality is Sly, DNA Digivolution' WHERE id = 494;
UPDATE digimon_en SET digimon_type = 'Bulb', evolution_condition = 'Agent Rank >= 1, INT >= 160' WHERE id = 510;
UPDATE digimon_en SET digimon_type = 'Bulb', evolution_condition = 'Agent Rank >= 1, HP >= 370, INT >= 140' WHERE id = 512;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, MP >= 360, INT >= 180' WHERE id = 514;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, MP >= 160, SPD >= 150' WHERE id = 515;
UPDATE digimon_en SET digimon_type = 'Mythical Beast', evolution_condition = 'Agent Rank >= 3, SPI >= 250, SPD >= 300' WHERE id = 548;
UPDATE digimon_en SET digimon_type = 'Mammal', evolution_condition = 'Agent Rank >= 1, MP >= 200, INT >= 160' WHERE id = 564;
UPDATE digimon_en SET digimon_type = 'Lesser', evolution_condition = 'Agent Rank >= 1, MP >= 280' WHERE id = 567;
UPDATE digimon_en SET digimon_type = 'Mammal', evolution_condition = 'Agent Rank >= 1, HP >= 400, SPD >= 230' WHERE id = 569;
UPDATE digimon_en SET digimon_type = 'Baby Bird', evolution_condition = 'Agent Rank >= 1, ATK >= 200, SPD >= 170' WHERE id = 573;
UPDATE digimon_en SET digimon_type = 'Bird Man', evolution_condition = 'Agent Rank >= 3, MP >= 400, ATK >= 530' WHERE id = 574;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 5, SPI >= 960, SPD >= 1040' WHERE id = 575;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 5, HP >= 1530, INT >= 1020' WHERE id = 576;
UPDATE digimon_en SET digimon_type = 'Demon', evolution_condition = 'Agent Rank >= 1, MP >= 230, SPD >= 230' WHERE id = 577;
UPDATE digimon_en SET digimon_type = 'Demon', evolution_condition = 'Agent Rank >= 1, MP >= 300' WHERE id = 578;
UPDATE digimon_en SET digimon_type = 'Demon', evolution_condition = 'Agent Rank >= 3, MP >= 380, ATK >= 640' WHERE id = 579;
UPDATE digimon_en SET digimon_type = 'Ice-Snow', evolution_condition = 'Agent Rank >= 3, HP >= 1010, ATK >= 380' WHERE id = 580;
UPDATE digimon_en SET digimon_type = 'Amphibian', evolution_condition = 'Agent Rank >= 1, ATK >= 150, DEF >= 140' WHERE id = 582;
UPDATE digimon_en SET digimon_type = 'Ghost', evolution_condition = 'Agent Rank >= 5, HP >= 1530, SPI >= 940, SPD >= 1010' WHERE id = 584;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 3, ATK >= 620' WHERE id = 586;
UPDATE digimon_en SET digimon_type = 'Ancient Beast', evolution_condition = 'Agent Rank >= 5, HP >= 1940, ATK >= 820' WHERE id = 588;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 3, HP >= 900' WHERE id = 590;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 3, MP >= 460, ATK >= 380' WHERE id = 592;
UPDATE digimon_en SET digimon_type = 'Sea Animal', evolution_condition = 'Agent Rank >= 1, MP >= 400, SPI >= 210' WHERE id = 594;
UPDATE digimon_en SET digimon_type = 'Ore', evolution_condition = 'Agent Rank >= 1, DEF >= 170, SPI >= 190' WHERE id = 595;
UPDATE digimon_en SET digimon_type = 'Puppet', evolution_condition = 'Agent Rank >= 5, HP >= 1610, INT >= 1060' WHERE id = 596;
UPDATE digimon_en SET digimon_type = 'Insectoid', evolution_condition = 'Agent Rank >= 3, SPD >= 530' WHERE id = 597;
UPDATE digimon_en SET digimon_type = 'Dinosaur', evolution_condition = 'Agent Rank >= 3, ATK >= 540' WHERE id = 598;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 7, HP >= 2080, ATK >= 2140' WHERE id = 600;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 3, INT >= 500, SPI >= 490' WHERE id = 601;
UPDATE digimon_en SET digimon_type = 'Magic Warrior', evolution_condition = 'Agent Rank >= 5, MP >= 550, INT >= 900, SPI >= 890' WHERE id = 602;
UPDATE digimon_en SET digimon_type = 'Warrior', evolution_condition = 'Agent Rank >= 7, INT >= 2050, SPI >= 1790' WHERE id = 603;
UPDATE digimon_en SET digimon_type = 'Galaxy', evolution_condition = 'Agent Rank >= 8, Apollomon''s personnality is Daring, Dianamon''s personnality is Enlightened, DNA Digivolution' WHERE id = 604;
UPDATE digimon_en SET digimon_type = 'Ancient Crustacean', evolution_condition = 'Agent Rank >= 5, MP >= 920, DEF >= 1060' WHERE id = 605;
UPDATE digimon_en SET digimon_type = 'Aquatic', evolution_condition = 'Agent Rank >= 5, HP >= 1610, ATK >= 860, SPD >= 830' WHERE id = 606;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 1, DEF >= 200' WHERE id = 607;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 1, HP >= 420, ATK >= 160' WHERE id = 609;
UPDATE digimon_en SET digimon_type = 'Ancient Bird', evolution_condition = 'Agent Rank >= 3, MP >= 510' WHERE id = 610;
UPDATE digimon_en SET digimon_type = 'Vegetation', evolution_condition = 'Agent Rank >= 1, MP >= 280, INT >= 200' WHERE id = 611;
UPDATE digimon_en SET digimon_type = 'Virtue', evolution_condition = 'Agent Rank >= 7, MP >= 1540, INT >= 2450' WHERE id = 613;
UPDATE digimon_en SET digimon_type = 'Great Angel', evolution_condition = 'Agent Rank >= 7, ATK >= 2050, SPD >= 1060' WHERE id = 614;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 3, HP >= 870, DEF >= 430' WHERE id = 615;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 7, MP >= 1200, ATK >= 1940' WHERE id = 616;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 7, HP >= 2500, ATK >= 1940' WHERE id = 617;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 3, DEF >= 430, SPI >= 300' WHERE id = 621;
UPDATE digimon_en SET digimon_type = 'Bird', evolution_condition = 'Agent Rank >= 1, INT >= 260' WHERE id = 622;
UPDATE digimon_en SET digimon_type = 'Bird', evolution_condition = 'Agent Rank >= 1, HP >= 500, MP >= 270' WHERE id = 623;
UPDATE digimon_en SET digimon_type = 'Unidentified', evolution_condition = 'Agent Rank >= 1, HP >= 530, MP >= 260' WHERE id = 626;
UPDATE digimon_en SET digimon_type = 'Unidentified', evolution_condition = 'Agent Rank >= 5, MP >= 660, ATK >= 1110, SPD >= 930' WHERE id = 627;
UPDATE digimon_en SET digimon_type = 'Unidentified', evolution_condition = 'Agent Rank >= 1' WHERE id = 629;
UPDATE digimon_en SET digimon_type = 'Unidentified', evolution_condition = 'Agent Rank >= 3, HP >= 1170' WHERE id = 630;
UPDATE digimon_en SET digimon_type = 'Unidentified', evolution_condition = 'Agent Rank >= 1, MP >= 260, ATK >= 170' WHERE id = 631;
UPDATE digimon_en SET digimon_type = 'Unidentified', evolution_condition = 'Agent Rank >= 7, HP >= 2690, ATK >= 2250' WHERE id = 632;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 5, Have Beast Spirit of Flame' WHERE id = 669;
UPDATE digimon_en SET digimon_type = 'Warrior', evolution_condition = 'Agent Rank >= 5, Have Beast Spirit of Light' WHERE id = 670;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7' WHERE id = 675;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 3, Have Human Spirit of Flame' WHERE id = 676;
UPDATE digimon_en SET digimon_type = 'Dragon Warrior', evolution_condition = 'Agent Rank >= 7' WHERE id = 677;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7' WHERE id = 678;
UPDATE digimon_en SET digimon_type = 'Dark Dragon', evolution_condition = 'Agent Rank >= 3, Have Beast Spirit of Flame' WHERE id = 679;
UPDATE digimon_en SET digimon_type = 'Warrior', evolution_condition = 'Agent Rank >= 3, Have Human Spirit of Light' WHERE id = 680;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 3, Have Beast Spirit of Light' WHERE id = 681;
UPDATE digimon_en SET digimon_type = 'Mini Dragon', evolution_condition = 'Agent Rank >= 1, HP >= 500, ATK >= 270' WHERE id = 682;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 5, HP >= 1070, MP >= 320' WHERE id = 683;
UPDATE digimon_en SET digimon_type = 'Mini Dragon', evolution_condition = 'Agent Rank >= 1, HP >= 420' WHERE id = 687;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, DEF >= 1860, SPI >= 1720' WHERE id = 688;
UPDATE digimon_en SET digimon_type = 'Weapon', evolution_condition = 'Agent Rank >= 1, ATK >= 280, DEF >= 200' WHERE id = 697;
UPDATE digimon_en SET digimon_type = 'Weapon', evolution_condition = 'Agent Rank >= 3, ATK >= 540' WHERE id = 698;
UPDATE digimon_en SET digimon_type = 'Weapon', evolution_condition = 'Agent Rank >= 5, HP >= 1900, ATK >= 1060, DEF >= 960' WHERE id = 699;
UPDATE digimon_en SET digimon_type = 'Holy Sword', evolution_condition = 'Agent Rank >= 7, HP >= 2360, ATK >= 1580, DEF >= 1740' WHERE id = 700;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, HP >= 380, ATK >= 180' WHERE id = 701;
UPDATE digimon_en SET digimon_type = 'Bird', evolution_condition = 'Agent Rank >= 3, SPD >= 540' WHERE id = 702;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, MP >= 1120, SPI >= 2020, SPD >= 2060' WHERE id = 703;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 7, DEF >= 2250, SPI >= 1850' WHERE id = 704;
UPDATE digimon_en SET digimon_type = 'Bird', evolution_condition = 'Agent Rank >= 1, INT >= 230, SPD >= 180' WHERE id = 705;
UPDATE digimon_en SET digimon_type = 'Bird', evolution_condition = 'Agent Rank >= 1, ATK >= 180, SPD >= 180' WHERE id = 706;
UPDATE digimon_en SET digimon_type = 'Mammal', evolution_condition = 'Agent Rank >= 1, MP >= 400, SPD >= 250' WHERE id = 707;
UPDATE digimon_en SET digimon_type = 'Puppet', evolution_condition = 'Agent Rank >= 1, HP >= 460' WHERE id = 708;
UPDATE digimon_en SET digimon_type = 'Crustacean', evolution_condition = 'Agent Rank >= 1, HP >= 440, DEF >= 180' WHERE id = 709;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 3, MP >= 530' WHERE id = 710;
UPDATE digimon_en SET digimon_type = 'Armored Dragon', evolution_condition = 'Agent Rank >= 3, DEF >= 450, SPI >= 420' WHERE id = 711;
UPDATE digimon_en SET digimon_type = 'Dinosaur', evolution_condition = 'Agent Rank >= 3, ATK >= 660, SPI >= 420, SPD >= 540' WHERE id = 712;
UPDATE digimon_en SET digimon_type = 'Reptile', evolution_condition = 'Agent Rank >= 1, ATK >= 360' WHERE id = 713;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 3, SPD >= 580' WHERE id = 714;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 5, MP >= 620, ATK >= 980, SPI >= 920, SPD >= 1020' WHERE id = 715;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 3, Have Digi-Egg of Courage' WHERE id = 716;
UPDATE digimon_en SET digimon_type = 'Warrior', evolution_condition = 'Agent Rank >= 5, DEF >= 1040, SPI >= 950' WHERE id = 718;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, MP >= 510, ATK >= 960, DEF >= 790' WHERE id = 719;
UPDATE digimon_en SET digimon_type = 'Beast Man', evolution_condition = 'Agent Rank >= 5, Aquilamon''s personnality is Sociable, Gatomon''s personnality is Tolerant, DNA Digivolution' WHERE id = 720;
UPDATE digimon_en SET digimon_type = 'Mysterious Bird', evolution_condition = 'Agent Rank >= 5, INT >= 1020, SPD >= 1050' WHERE id = 721;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, MP >= 1150, SPD >= 1020' WHERE id = 722;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 5, Ankylomon''s personnality is Overprotective, Angemon''s personnality is Enlightened, DNA Digivolution' WHERE id = 723;
UPDATE digimon_en SET digimon_type = 'Plesiosaur', evolution_condition = 'Agent Rank >= 5, HP >= 1650, SPI >= 1010' WHERE id = 724;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, HP >= 2900, DEF >= 2130, SPI >= 1570' WHERE id = 725;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 5, MP >= 1100, INT >= 1650' WHERE id = 726;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, MP >= 540, ATK >= 1060' WHERE id = 727;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 1, MP >= 290, SPI >= 200' WHERE id = 728;
UPDATE digimon_en SET digimon_type = 'Mollusk', evolution_condition = 'Agent Rank >= 3, HP >= 750' WHERE id = 729;
UPDATE digimon_en SET digimon_type = 'Dark Angel', evolution_condition = 'Agent Rank >= 3, ATK >= 400, SPI >= 300' WHERE id = 730;
UPDATE digimon_en SET digimon_type = 'Holy Beast', evolution_condition = 'Agent Rank >= 5, MP >= 920, SPD >= 990' WHERE id = 731;
UPDATE digimon_en SET digimon_type = 'Ancient Dragon', evolution_condition = 'Agent Rank >= 7, HP >= 2890, MP >= 1180, SPI >= 1180' WHERE id = 732;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, DEF >= 1670, INT >= 2100' WHERE id = 733;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, HP >= 2380, DEF >= 1850, SPI >= 1540' WHERE id = 734;
UPDATE digimon_en SET digimon_type = 'Cherub', evolution_condition = 'Agent Rank >= 7, MP >= 1260, INT >= 2140, SPI >= 1600' WHERE id = 735;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, DEF >= 2060, SPI >= 1960' WHERE id = 737;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, HP >= 2500, ATK >= 1940, SPD >= 1660' WHERE id = 738;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, HP >= 2570, INT >= 2130, SPD >= 1890' WHERE id = 739;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, MP >= 1640, SPD >= 1820' WHERE id = 740;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 7, HP >= 2500, MP >= 1070, ATK >= 1780' WHERE id = 741;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 7, HP >= 2380, MP >= 1100, INT >= 1980' WHERE id = 742;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7' WHERE id = 743;
UPDATE digimon_en SET digimon_type = 'Dragon Man', evolution_condition = 'Agent Rank >= 7, HP >= 2820, ATK >= 2430' WHERE id = 744;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, HP >= 2820, ATK >= 1900, SPD >= 1600' WHERE id = 745;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, HP >= 2360, ATK >= 1940' WHERE id = 747;
UPDATE digimon_en SET digimon_type = 'Angel', evolution_condition = 'Agent Rank >= 7, Angewomon''s personnality is Tolerant, LadyDevimon''s personnality is Enlightened, DNA Digivolution' WHERE id = 748;
UPDATE digimon_en SET digimon_type = 'Holy Knight', evolution_condition = 'Agent Rank >= 7, ATK >= 1730, DEF >= 1730, SPD >= 1650' WHERE id = 749;
UPDATE digimon_en SET digimon_type = 'Beast', evolution_condition = 'Agent Rank >= 1, MP >= 280, DEF >= 170' WHERE id = 750;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, Have Digi-Egg of Destiny' WHERE id = 751;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 3, DEF >= 550' WHERE id = 752;
UPDATE digimon_en SET digimon_type = 'Mollusk', evolution_condition = 'Agent Rank >= 5, HP >= 1720, DEF >= 900' WHERE id = 753;
UPDATE digimon_en SET digimon_type = 'Deity', evolution_condition = 'Agent Rank >= 7, MP >= 1290, INT >= 1860, SPI >= 1290' WHERE id = 754;
UPDATE digimon_en SET digimon_type = 'Wizard', evolution_condition = 'Agent Rank >= 3, INT >= 640, SPI >= 480' WHERE id = 755;
UPDATE digimon_en SET digimon_type = 'Ore', evolution_condition = 'Agent Rank >= 5, DEF >= 980, SPI >= 970' WHERE id = 756;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, BlackWarGreymon''s personnality is Reckless, MetalGarurumon (Black)''s personnality is Friendly, DNA Digivolution' WHERE id = 757;
UPDATE digimon_en SET digimon_type = 'Ice-Snow', evolution_condition = 'Agent Rank >= 3, ATK >= 460, SPI >= 620' WHERE id = 758;
UPDATE digimon_en SET digimon_type = 'Mutant', evolution_condition = 'Agent Rank >= 3, MP >= 380' WHERE id = 759;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 3, DEF >= 500, SPI >= 380' WHERE id = 760;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, Alphamon''s personnality is Friendly, Ouryumon''s personnality is Zealous, DNA Digivolution' WHERE id = 766;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, HP >= 4250, ATK >= 2850' WHERE id = 767;
UPDATE digimon_en SET digimon_type = 'Machine', evolution_condition = 'Agent Rank >= 5, ATK >= 1150, DEF >= 900' WHERE id = 770;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 7, HP >= 2400, ATK >= 2220' WHERE id = 771;
UPDATE digimon_en SET digimon_type = 'Unique', evolution_condition = 'Agent Rank >= 8, Darkdramon''s personnality is Zealous, BanchoLeomon''s personnality is Daring, DNA Digivolution' WHERE id = 772;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, MP >= 1930, SPD >= 1650' WHERE id = 773;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 7, MP >= 960, INT >= 2280, SPI >= 1600' WHERE id = 774;
UPDATE digimon_en SET digimon_type = 'Evil King', evolution_condition = 'Agent Rank >= 8, ATK >= 3760, SPD >= 2960' WHERE id = 775;
UPDATE digimon_en SET digimon_type = 'Shining Dragon', evolution_condition = 'Agent Rank >= 8, HP >= 4900, SPD >= 2810' WHERE id = 776;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, ATK >= 3100, SPD >= 3100' WHERE id = 777;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 8, MP >= 1710, SPD >= 3390' WHERE id = 778;
UPDATE digimon_en SET digimon_type = 'Pixie', evolution_condition = 'Agent Rank >= 8, INT >= 3170, SPI >= 2700' WHERE id = 779;
UPDATE digimon_en SET digimon_type = 'Cyborg', evolution_condition = 'Agent Rank >= 5, HP >= 1690, MP >= 960, ATK >= 1100' WHERE id = 907;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, MP >= 1350, INT >= 1230' WHERE id = 908;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 7, ATK >= 2500, INT >= 1900' WHERE id = 912;
UPDATE digimon_en SET evolution_condition = 'Agent Rank >= 8, Titamon''s personnality is Reckless, SkullBaluchimon''s personnality is Sociable, DNA Digivolution' WHERE id = 915;
UPDATE digimon_en SET digimon_type = 'Undead', evolution_condition = 'Agent Rank >= 5, HP >= 1140, DEF >= 820, SPD >= 840' WHERE id = 920;

-- Official Encyclopedia type fallback for variants without their own reference_en page.
UPDATE digimon_en SET digimon_type = 'Puppet' WHERE digimon_type = '퍼펫형';
UPDATE digimon_en SET digimon_type = 'Ceratopsian' WHERE digimon_type = '각룡형';
UPDATE digimon_en SET digimon_type = 'Deity' WHERE digimon_type = '신인형';
UPDATE digimon_en SET digimon_type = 'Cyborg' WHERE digimon_type IN ('사이보그형', '안드로이드형');
UPDATE digimon_en SET digimon_type = 'Unidentified' WHERE digimon_type = '종족불명';
UPDATE digimon_en SET digimon_type = 'Aquatic Beast Man' WHERE digimon_type = '수생수인형';
UPDATE digimon_en SET digimon_type = 'Beast Man' WHERE digimon_type = '수인형';
UPDATE digimon_en SET digimon_type = 'Beast Dragon' WHERE digimon_type IN ('짐승룡형', '짐승용형');
UPDATE digimon_en SET digimon_type = 'Wizard' WHERE digimon_type = '마법사형';
UPDATE digimon_en SET digimon_type = 'Mythical Dragon' WHERE digimon_type = '신룡형';
UPDATE digimon_en SET digimon_type = 'Demon' WHERE digimon_type = '악마형';
UPDATE digimon_en SET digimon_type = 'Holy Dragon' WHERE digimon_type = '성룡형';
UPDATE digimon_en SET digimon_type = 'Insectoid' WHERE digimon_type = '곤충형';
UPDATE digimon_en SET digimon_type = 'Unique' WHERE digimon_type = '특수형';
UPDATE digimon_en SET digimon_type = 'Holy Knight' WHERE digimon_type = '성기사형';
UPDATE digimon_en SET digimon_type = 'Machine' WHERE digimon_type = '머신형';
UPDATE digimon_en SET digimon_type = 'Holy Bird' WHERE digimon_type = '성조형';
UPDATE digimon_en SET digimon_type = 'Cherub' WHERE digimon_type = '짐승천사형';
UPDATE digimon_en SET digimon_type = 'Beast' WHERE digimon_type = '짐승형';
